openapi: 3.0.0
info:
  version: 1.0.0
  title: Yotas API

servers:
  - url: http://localhost:8080/v1
  - url: https://api.yotas.app/v1

# Bearer Authentication
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /users:
    $ref: "./paths/user.yaml"
  /users/{userId}:
    $ref: "./paths/user-id.yaml"
